# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import helloworld_pb2 as helloworld__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in helloworld_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/helloworld.Greeter/SayHello',
                request_serializer=helloworld__pb2.HelloRequest.SerializeToString,
                response_deserializer=helloworld__pb2.HelloReply.FromString,
                _registered_method=True)
        self.NextDate = channel.unary_unary(
                '/helloworld.Greeter/NextDate',
                request_serializer=helloworld__pb2.RequestDate.SerializeToString,
                response_deserializer=helloworld__pb2.ReplyDate.FromString,
                _registered_method=True)
        self.AddDaysDate = channel.unary_unary(
                '/helloworld.Greeter/AddDaysDate',
                request_serializer=helloworld__pb2.RequestAddDay.SerializeToString,
                response_deserializer=helloworld__pb2.ReplyDate.FromString,
                _registered_method=True)
        self.DimeCentroDiana = channel.unary_unary(
                '/helloworld.Greeter/DimeCentroDiana',
                request_serializer=helloworld__pb2.Empty.SerializeToString,
                response_deserializer=helloworld__pb2.CentroDianaResponse.FromString,
                _registered_method=True)
        self.DisparaCannon = channel.unary_unary(
                '/helloworld.Greeter/DisparaCannon',
                request_serializer=helloworld__pb2.DisparoRequest.SerializeToString,
                response_deserializer=helloworld__pb2.DisparoResponse.FromString,
                _registered_method=True)
        self.MejorDisparo = channel.unary_unary(
                '/helloworld.Greeter/MejorDisparo',
                request_serializer=helloworld__pb2.Empty.SerializeToString,
                response_deserializer=helloworld__pb2.MejorDisparoResponse.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NextDate(self, request, context):
        """metodo para calcular la fecha del dia siguiente 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDaysDate(self, request, context):
        """metodo suma dias
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DimeCentroDiana(self, request, context):
        """Metodos para el servicio de disparos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisparaCannon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MejorDisparo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=helloworld__pb2.HelloRequest.FromString,
                    response_serializer=helloworld__pb2.HelloReply.SerializeToString,
            ),
            'NextDate': grpc.unary_unary_rpc_method_handler(
                    servicer.NextDate,
                    request_deserializer=helloworld__pb2.RequestDate.FromString,
                    response_serializer=helloworld__pb2.ReplyDate.SerializeToString,
            ),
            'AddDaysDate': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDaysDate,
                    request_deserializer=helloworld__pb2.RequestAddDay.FromString,
                    response_serializer=helloworld__pb2.ReplyDate.SerializeToString,
            ),
            'DimeCentroDiana': grpc.unary_unary_rpc_method_handler(
                    servicer.DimeCentroDiana,
                    request_deserializer=helloworld__pb2.Empty.FromString,
                    response_serializer=helloworld__pb2.CentroDianaResponse.SerializeToString,
            ),
            'DisparaCannon': grpc.unary_unary_rpc_method_handler(
                    servicer.DisparaCannon,
                    request_deserializer=helloworld__pb2.DisparoRequest.FromString,
                    response_serializer=helloworld__pb2.DisparoResponse.SerializeToString,
            ),
            'MejorDisparo': grpc.unary_unary_rpc_method_handler(
                    servicer.MejorDisparo,
                    request_deserializer=helloworld__pb2.Empty.FromString,
                    response_serializer=helloworld__pb2.MejorDisparoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helloworld.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/SayHello',
            helloworld__pb2.HelloRequest.SerializeToString,
            helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NextDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/NextDate',
            helloworld__pb2.RequestDate.SerializeToString,
            helloworld__pb2.ReplyDate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDaysDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/AddDaysDate',
            helloworld__pb2.RequestAddDay.SerializeToString,
            helloworld__pb2.ReplyDate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DimeCentroDiana(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/DimeCentroDiana',
            helloworld__pb2.Empty.SerializeToString,
            helloworld__pb2.CentroDianaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisparaCannon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/DisparaCannon',
            helloworld__pb2.DisparoRequest.SerializeToString,
            helloworld__pb2.DisparoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MejorDisparo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/MejorDisparo',
            helloworld__pb2.Empty.SerializeToString,
            helloworld__pb2.MejorDisparoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
